spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manito
    username: manito
    password: manito-pw
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,public/**
    livereload:
      enabled: true

server :
  port : 5055